# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "{{ cookiecutter.memory }}"
  end
  
  config.vm.define "{{ cookiecutter.hostname }}" do |hostconfig|
    hostconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/{{ cookiecutter.hostname}}.yml"
    end
  end
end
